### ISSUE TITLE
$secret

### ISSUE THREAD

**Issue by ackerrr** [Oxycoin/oxy-checker#2]
Hi Jan! What is this mean? 

>If you want to forge multiple, add extra to the array

`$secret         = array("");                            // Add your secrets here. If you want to forge multiple, add extra to the array.`

Can I add here two secrets to start forging for two delegates on one node?

> delegate 1 = oxy;
> delegate 2 = coin;

`$secret         = array("oxy oxy oxy oxy oxy oxy oxy oxy oxy oxy oxy oxy", "coin coin coin coin coin coin coin coin coin coin coin coin");`

Am I understand it right?

**Comment by crypt0jan** [comment]
I explained it to you on Telegram already, but for the sake of closing this ticket: yes exactly!

**Comment by ackerrr** [comment]
Thanks again!
